# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0002_remove_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
