# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('travelstartdate', models.DateField(auto_now_add=True)),
                ('travelenddate', models.DateField(auto_now=True)),
            ],
        ),
    ]
