# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0002_remove_user_last_name'),
        ('add_plan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='users',
            field=models.ManyToManyField(to='login_and_registration_app.User'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='add_plan_app.Plan'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login_and_registration_app.User'),
        ),
    ]
