# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_plan_app', '0002_auto_20161021_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseUser',
            new_name='PlanUser',
        ),
    ]
