# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_plan_app', '0003_auto_20161021_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planuser',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='planuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='PlanUser',
        ),
    ]
