# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0003_auto_20161024_2255'),
        ('add_plan_app', '0005_auto_20161025_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_created', to='login_and_registration_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='users',
            field=models.ManyToManyField(related_name='plans_joined', to='login_and_registration_app.User'),
        ),
    ]
